added nodeVolumeAttachLimit
gardener/gardener-extension-provider-openstack pull request #160
Opened 2020-10-09 11:14 UTC by mganter

**How to categorize this PR?**

/area robustness
/area storage
/kind enhancement
/priority normal
/platform openstack

**What this PR does / why we need it**:
The introduced flag tells the CSI-Driver, that there is a upper limit for mounted volumes on a node. 

**Release note**:

```improvement operator
Added possibility to set nodeVolumeAttachLimit within the cloud profile.
```

2020-10-09 11:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardener-extension-provider-openstack?pullRequest=160) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardener-extension-provider-openstack?pullRequest=160) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardener-extension-provider-openstack?pullRequest=160) it.</sub>

2020-10-12 18:42 UTC, dkistner commented
Hi @mganter.
Thanks you very much for the PR. 
I will have a look soon.

2020-10-15 20:05 UTC, dkistner reviewed
Thanks @mganter 
I had a brief look. Can you elaborate a little bit on the reasons why the amount of volumes per node need to be limited?
Should that not rather be configured for each `Shoot` cluster individually instead of globally via the `CloudProfile`?

2020-10-16 07:24 UTC, mganter commented
The limit exists inside of OpenStack. With this option you can tell the scheduler, that he shall not schedule more cinder volumes to a specific node than the specified amount. 

If the scheduler does't know it, he will schedule pods to nodes where they can't be satisfied in terms of volumes. So pods will remain in container creation state.

2020-10-19 20:05 UTC, dkistner requested changes
Thanks for explanation. I played a little bit around with it and configured a limit of just two disks per node.
If I try to schedule more pods with disk to a node the schedules tells:
```
I1019 19:50:13.426597       1 factory.go:445] "Unable to schedule pod; no fit; waiting" pod="default/some-persistence-2" err="0/1 nodes are available: 1 node(s) exceed max volume count."
```
Also there is an event which indicate the same:
```
2m34s       Warning   FailedScheduling          pod/some-persistence-2                                            0/1 nodes are available: 1 node(s) exceed max volume count.
```

The pr looks overall very nice. The tests for the valuesprovider/controlplane controller needs to be adapted. They fail because the new property `nodeVolumeAttachLimit` is missing here: https://github.com/gardener/gardener-extension-provider-openstack/blob/master/pkg/controller/controlplane/valuesprovider_test.go#L247-L262 

We should also mention in the [operator docs](https://github.com/gardener/gardener-extension-provider-openstack/blob/master/docs/usage-as-operator.md#cloudprofileconfig) that this feature will only be available when using CSI.

2020-10-20 11:40 UTC, mganter commented
Added docs. Updated test.

2020-10-20 12:51 UTC, dkistner approved these changes

2020-10-20 12:53 UTC, rfranzke approved these changes

2020-10-21 06:42 UTC, rfranzke commented
/reviewed ok-to-test

2020-10-21 07:02 UTC, rfranzke commented
@mganter can you check the failing CI? probably you need to run `make generate`

2020-10-21 11:51 UTC, mganter commented
> @mganter can you check the failing CI? probably you need to run `make generate`
> /status author-action

`make generate` results in no change of code. Removing `controller-registration.yaml` results in recreating it exactly with no diff. I rebased it to the latest rev. 

Some system information:
I'm running Manjaro Kernel: Linux 5.8.11-1-MANJARO
ldd (GNU libc) 2.32

Do you know if there are any issues with that?

2020-10-21 11:54 UTC, rfranzke commented
Now there is a conflict.

> Do you know if there are any issues with that?

Hm, good question, can you run `make install-requirements` and try again?

2020-10-21 12:03 UTC, mganter commented
The conflict is resolved now. (Didn't have the changes from 1 hour ago)
And its re-generated.

2020-10-21 12:17 UTC, rfranzke approved these changes

2020-10-21 12:18 UTC, merged

2020-10-21 12:18 UTC, rfranzke commented
Thanks @mganter!

2020-10-21 12:19 UTC, mganter commented
Thank you very much  @rfranzke @dkistner