Floating Subnet Config: Wildcards and Defaults
gardener/gardener-extension-provider-openstack pull request #237
Opened 2021-03-01 15:13 UTC by dkistner

**How to categorize this PR?**

/kind enhancement
/priority normal
/platform openstack

**What this PR does / why we need it**:
Allow to configure a default subnet for floating pool configurations in the CloudProfile.
This will be used to assign the router interface of a Shoot cluster (if not an existing router is used) to the matching subnet.
Furthermore enable the selection of floating pool subnets by wildcards.

In addition it is now forbidden to change the floating pool or the floating pool subnet configuration as this is not supported by Neutron.

This change require a Terraformer with openstack provider `v1.37` or higher. 
The floating subnet id field is removed from the Infrastructure state as it was unused.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener-extension-provider-openstack/issues/219

**Special notes for your reviewer**:

**Release note**:

```feature operator
Allow to configure a default subnet for floating pools configuration in the CloudProfile and enable the selection of floating pool subnet by wildcards.
```

```feature user
Enable the selection of floating pool subnet by wildcards.
```

**Will keep it as draft as there is a final test ongoing.**

/invite @kon-angelo @MartinWeindel 

cc @RaphaelVogel  @kayrus

2021-03-02 17:10 UTC, MartinWeindel requested changes
lgtm, I only found some minor typos.

2021-03-02 17:10 UTC, MartinWeindel commented on pkg/apis/openstack/helper/helper.go
> +		maxCanidateScore             int
```suggestion
		maxCandidateScore             int
```

2021-03-02 17:10 UTC, MartinWeindel commented on pkg/apis/openstack/helper/helper.go
> +// match for a given `floatingPoolNamePattern` considering contraints like
```suggestion
// match for a given `floatingPoolNamePattern` considering constraints like
```

2021-03-02 17:10 UTC, MartinWeindel commented on pkg/apis/openstack/types_infrastructure.go
> +	// in the FLoating IP Pool where the router should be attached to.
```suggestion
	// in the Floating IP Pool where the router should be attached to.
```

2021-03-02 17:10 UTC, MartinWeindel commented on pkg/apis/openstack/v1alpha1/types_infrastructure.go
> +	// in the FLoating IP Pool where the router should be attached to.
```suggestion
	// in the Floating IP Pool where the router should be attached to.
```

2021-03-03 10:39 UTC, dkistner commented
Thanks @MartinWeindel done :)

2021-03-03 11:06 UTC, MartinWeindel approved these changes
/lgtm

2021-03-08 11:11 UTC, kon-angelo commented on pkg/apis/openstack/helper/helper.go
> +		if candiate, score := checkFloatingPoolCandidate(&fip, floatingPoolNamePattern, region, domain); candiate != nil && score > maxCandidateScore {
`candidate` typo

2021-03-09 10:46 UTC, dkistner commented on pkg/apis/openstack/helper/helper.go
> +		if candiate, score := checkFloatingPoolCandidate(&fip, floatingPoolNamePattern, region, domain); candiate != nil && score > maxCandidateScore {
done. Thanks

2021-03-09 12:56 UTC, merged