disable network overlay for cilium by default
gardener/gardener-extension-provider-openstack pull request #517
Opened 2022-11-24 10:27 UTC by DockToFuture

**How to categorize this PR?**

/area networking
/kind enhancement
/platform openstack

**What this PR does / why we need it**:
Overlay networks for newly created cilium shoot clusters are dropped now by default. To keep the overlay network `networking.providerConfig.overlay.enabled: true` needs to be set explicitly in the shoot spec.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Overlay networks for newly created cilium shoot clusters are dropped now by default. To keep the overlay network `networking.providerConfig.overlay.enabled: true` needs to be set explicitly in the shoot spec.
```

2023-01-30 15:18 UTC, DockToFuture commented
/cc: @ScheererJ

2023-01-30 15:43 UTC, ScheererJ submitted a review, later dismissed
/lgtm

2023-01-31 13:47 UTC, DockToFuture commented on cmd/gardener-extension-admission-openstack/app/app.go
> +
No its not necessary with this approach any more I've updated it.

2023-01-31 15:47 UTC, ScheererJ requested changes

2023-01-31 15:47 UTC, ScheererJ commented on pkg/admission/mutator/shoot.go
> +		}
Indeed, we probably only want to execute the `if` block in case `networkConfig.Overlay != nil`.
(The same is true above in the calico case.)

2023-01-31 15:54 UTC, kon-angelo commented on pkg/admission/mutator/shoot.go
> +		}
If so, I would suggest we reconsider the "globally" part of the name to something indicating default choice perhaps

2023-02-01 13:49 UTC, kon-angelo approved these changes
/lgtm

2023-02-01 13:50 UTC, merged