Add node.gardener.cloud/critical-component to csi-driver-node DaemonSet
gardener/gardener-extension-provider-openstack pull request #562
Opened 2023-02-02 14:21 UTC by dergeberl

**How to categorize this PR?**

/area robustness
/kind enhancement
/platform openstack

**What this PR does / why we need it**:

This PR adds the `node.gardener.cloud/critical-component` label to `csi-driver-node` introduced in https://github.com/gardener/gardener/pull/7406

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/7117

**Special notes for your reviewer**:

**Release note**:

```other operator
Add node.gardener.cloud/critical-component label to csi-driver-node DaemonSet.
```

2023-02-10 07:51 UTC, timebertt requested changes

2023-02-10 07:51 UTC, timebertt commented on charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
> +        node.gardener.cloud/critical-component: "true"
The label needs to be added to the `DaemonSet` metadata as well now, see https://github.com/gardener/gardener/issues/7117#issuecomment-1425346730.

2023-02-15 09:38 UTC, timebertt commented
/unhold
now that https://github.com/gardener/gardener/pull/7406 is merged

2023-02-15 10:43 UTC, dergeberl commented
/unhold

2023-02-16 15:17 UTC, kon-angelo approved these changes
/lgtm

2023-02-16 15:46 UTC, kon-angelo commented
@timebertt PTAL :)

2023-02-17 06:51 UTC, timebertt approved these changes
/lgtm

2023-02-17 08:29 UTC, merged