Switched from DockerHub to Gardener GCR
gardener/gardener-extension-provider-openstack pull request #592
Opened 2023-03-23 14:39 UTC by robinschneider

**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
This PR is needed to support IPv6 single stack and avoid DockerHub pull limits as it uses copied images from Gardener GCR instead.
Part of https://github.com/gardener/ci-infra/issues/619

**Release note**:

```other operator
Switched images from DockerHub to copies in Gardener GCR
```

2023-03-23 15:17 UTC, MartinWeindel requested changes
Thanks for your contribution.
Looks ok, but the images have not yet been included in the [images.yaml](https://github.com/gardener/ci-infra/blob/master/config/images/images.yaml) for copying in the ci-infra project.
Can you please update this list first?
Please also include the new versions from the PR #588

2023-03-23 16:12 UTC, timebertt commented
/hold
until https://github.com/gardener/ci-infra/pull/646 is merged

2023-03-24 07:08 UTC, MartinWeindel commented
/unhold

2023-03-24 07:08 UTC, MartinWeindel approved these changes
/lgtm

2023-03-24 08:45 UTC, merged