Kubernetes v1.27
gardener/gardener-extension-provider-openstack pull request #632
Opened 2023-05-30 05:02 UTC by ary1992

**How to categorize this PR?**

/area open-source usability
/kind enhancement
/platform vsphere
/exp intermediate
/topology garden seed shoot
/merge squash

**What this PR does / why we need it**:
This PR adds support for Kubernetes 1.27 to the extension.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6773

**Special notes for your reviewer**:
* I have successfully validated the functionality as follows:
  ? Create new clusters with versions < 1.27
  ? Create new clusters with version  = 1.27
  ? Upgrade old clusters from version 1.26 to version 1.27
  ? Delete clusters with versions < 1.27
  ? Delete clusters with version  = 1.27

**Release note**:

```feature user
The provider-vsphere extension does now support shoot clusters with Kubernetes version 1.27. You should consider the [Kubernetes release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md) before upgrading to 1.27. 
```

2023-06-09 13:34 UTC, ialidzhikov requested changes

2023-06-09 13:34 UTC, ialidzhikov commented on charts/images.yaml
> +  targetVersion: ">= 1.26.x"
```suggestion
  targetVersion: "1.26.x"
```

:)

2023-06-09 13:34 UTC, ialidzhikov commented on charts/images.yaml
>    - name: 'gardener.cloud/cve-categorisation'
You have to update `registry.k8s.io/provider-os/cinder-csi-plugin:v1.27.1` and `registry.k8s.io/provider-os/manila-csi-plugin:v1.27.1` images to be used for K8s 1.27 Shoots.

2023-06-13 06:39 UTC, ialidzhikov approved these changes
/lgtm
/squash

2023-06-15 09:27 UTC, kon-angelo commented
/needs rebase

2023-06-15 09:36 UTC, kon-angelo approved these changes
/lgtm

2023-06-15 10:41 UTC, merged