Cleanup1.26
gardener/gardener-extension-provider-openstack pull request #889
Opened 2024-10-30 14:10 UTC by RadaBDimitrova

**How to categorize this PR?**

/kind cleanup
/platform openstack

**What this PR does / why we need it**:

- [x] Drop support for Shoots, Seeds and Gardens with Kubernetes version <= 1.24.
- [x] Adapt PDBs to use unhealthyPodEvictionPolicy: AlwaysAllow unconditionally
- [x] Adapt service.kubernetes.io/topology-mode annotation
- [x] Adapt controlplane webhook

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/10339

**Special notes for your reviewer**:

In draft until the gardener/gardener PR is merged and released.

**Release note**:

```other operator
`provider-openstack` no longer supports Shoots with Кubernetes version <= 1.26.
```

2025-03-07 12:18 UTC, ialidzhikov requested changes

2025-03-07 12:18 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer.go
>  }
We should be able to remove this func and the `EnsureKubeSchedulerDeployment` func. 

Reasoning: The `ensurer` embeds `genericmutator.NoopEnsurer`: https://github.com/gardener/gardener-extension-provider-openstack/blob/362fec4e68fb19cd31795168848f00b3e7829828/pkg/webhook/controlplane/ensurer.go#L43-L46

The `genericmutator.NoopEnsurer` has empty implementations of the interface methods from the `Ensurer` interface: https://github.com/gardener/gardener/blob/3c5d1de62eefb57fa06abef35cd318dd900c9f77/extensions/pkg/webhook/controlplane/genericmutator/noopensurer.go#L21-L24

When we remove the `EnsureKubeSchedulerDeployment` func, it will not complain that a required interface method is not implemented. It will fall back to the `EnsureKubeSchedulerDeployment` implementation from the `NoopEnsurer` implementation.

2025-03-07 12:18 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer.go
> +func ensureClusterAutoscalerCommandLineArgs(_ *corev1.Container, _ *semver.Version) {
We should be able to remove this func and `EnsureClusterAutoscalerDeployment`. See the reasoning in the previous comment.

2025-03-07 12:18 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer.go
>  	}
Can we also remove this if statement?

2025-03-07 12:18 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer_test.go
>  		It("should add missing elements to kube-apiserver deployment (k8s >= 1.27, < 1.31)", func() {
```suggestion
		It("should add missing elements to kube-apiserver deployment (k8s < 1.31)", func() {
```

2025-03-07 12:18 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer_test.go
>  		It("should add missing elements to kube-controller-manager deployment (k8s >= 1.27)", func() {
`EnsureKubeControllerManagerDeployment` no longer does something based on the K8s version.

```suggestion
		It("should add missing elements to kube-controller-manager deployment", func() {
```

2025-03-07 12:18 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer.go
> +func ensureKubeControllerManagerCommandLineArgs(c *corev1.Container, _ *semver.Version) {
You could remove the no longer used arg:

```suggestion
func ensureKubeControllerManagerCommandLineArgs(c *corev1.Container) {
```

2025-03-07 12:21 UTC, ialidzhikov commented on README.md
> -| Kubernetes 1.26 | 1.26.0+ | [![Gardener v1.26 Conformance Tests](https://testgrid.k8s.io/q/summary/conformance-gardener/Gardener,%20v1.26%20OpenStack/tests_status?style=svg)](https://testgrid.k8s.i
You could update https://github.com/gardener/gardener-extension-provider-openstack/blob/d62fce2c2751a76f6c9ae591018c42df66ac7b10/hack/api-reference/api.json#L12 and https://github.com/gardener/gardener-extension-provider-openstack/blob/d62fce2c2751a76f6c9ae591018c42df66ac7b10/hack/api-reference/config.json#L20.

2025-03-07 12:21 UTC, ialidzhikov commented on README.md
> -| Kubernetes 1.26 | 1.26.0+ | [![Gardener v1.26 Conformance Tests](https://testgrid.k8s.io/q/summary/conformance-gardener/Gardener,%20v1.26%20OpenStack/tests_status?style=svg)](https://testgrid.k8s.i
You could clean up https://github.com/gardener/gardener-extension-provider-openstack/blob/a45ab37c3ee2e7ea09872defdbec5d50e428eabc/imagevector/images.yaml#L101-L128 and https://github.com/gardener/gardener-extension-provider-openstack/blob/a45ab37c3ee2e7ea09872defdbec5d50e428eabc/imagevector/images.yaml#L200-L227

2025-03-07 12:21 UTC, ialidzhikov commented on README.md
> -| Kubernetes 1.26 | 1.26.0+ | [![Gardener v1.26 Conformance Tests](https://testgrid.k8s.io/q/summary/conformance-gardener/Gardener,%20v1.26%20OpenStack/tests_status?style=svg)](https://testgrid.k8s.i
You could update https://github.com/gardener/gardener-extension-provider-openstack/blob/27c2dd0ffde32f871bff86ba3f022a5feb8c0fd8/pkg/controller/controlplane/valuesprovider_test.go#L227.

2025-03-11 15:36 UTC, ialidzhikov reviewed
Thank for addressing my review comments!
Final comments from my side.

2025-03-11 15:36 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer_test.go
> -			checkKubeSchedulerDeployment(dep, "1.25.0")
You could also remove the `checkKubeSchedulerDeployment` func. It is no longer used.

2025-03-11 15:36 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer_test.go
> -			checkClusterAutoscalerDeployment(dep, "1.26.0")
You could also remove the `checkClusterAutoscalerDeployment` func. It is no longer used.

2025-03-11 15:36 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer_test.go
>  			Entry("kubelet >= 1.27", eContextK8s127, semver.MustParse("1.27.1"), nil),
Similar to https://github.com/gardener/gardener-extension-provider-alicloud/pull/742#discussion_r1984992905 we could rework the unit test:
- it no longer needs to be a table test, there is only 1 test entry
- no longer depends on the k8s version

2025-03-12 07:53 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer_test.go
>  		)
Nit

```suggestion
		})
```

2025-03-12 07:58 UTC, ialidzhikov commented
/unhold

2025-03-12 12:51 UTC, ialidzhikov approved these changes
/lgtm

2025-03-17 14:29 UTC, kon-angelo approved these changes
/lgtm

2025-03-17 14:29 UTC, merged